### PR TITLE
Add Mike and Iván to maintainer list

### PR DESCRIPTION
**Pull request by mikemhenry**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mikemhenry** [comment]
@conda-forge-admin, please rerender

**Comment by mikemhenry** [comment]
I bumped the version number since the re-build will produce a different package than the one built the first time. This PR is because it doesn't look like any of the other methods of adding me to the maintainer list is working.

**Comment by mikemhenry** [comment]
@jaimergp @jchodera Could one of you merge this PR? This PR adds me and Iván to the maintainer list (and makes sure that if anyone ever uses an older version of openmoltools that they get the right openmm version.

**Comment by jchodera** [comment]
@mikemhenry : Won't incrementing the build number and adding the constraint mean that the 0 build will still be installed erroneously, or does the incremented build number fully override the previous build?

There's another mechanism to patch existing builds that we used with parmed:
https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/166

**Comment by mikemhenry** [comment]
@jchodera 
After this PR is merged, if someone does `conda install -c conda-forge openmoltools=0.8.7` then they will get the higher build number, which will then pull in the correct version of openmm. 

Currently if someone does `conda install -c conda-forge openmoltools` they will get a version of openmm that will not work with openmoltools. 

I'd rather not hack things in like that, we could ask the conda-forge people to remove the 0 build if needed. The only way it will get pulled in is if someone uses the full version, ie `openmoltools=0.8.7=pyhd8ed1ab_0` so I don't think it is an issue.

**Pull request merged**
